Update README.md
narze/torpleng pull request #204
Opened 2022-10-01 18:47 UTC by nf0

# Checklist

- [ ] [มี Pull Request อื่นรออยู่](https://github.com/narze/torpleng/pulls?q=is%3Apr+is%3Aopen+sort%3Aupdated-desc) และต่อเพลงจาก Pull Request นั้น (เว้น 1 บรรทัดให้กับ PR ก่อนหน้าจะทำให้ไม่เกิด Git Conflict)
- [x] เนื้อเพลงล่าสุด (จากบรรทัดล่าสุดที่เห็น หรือจาก Pull Request ล่าสุด) : (ภาษา)กาย มันบอกลาที่ตรงหัวใจดีกว่าพูดจา
- [x] เนื้อเพลงที่นำมาต่อ : พูดจาภาษาเดิม หัวเติมต่อท้าย พูดจาภาษาไทย จริงใจอย่างนี้ไทยไทย
- [x] ได้ใส่ชื่อศิลปิน หรือวง ตามด้วยชื่อเพลง ตาม Format ที่กำหนดไว้แล้ว
- [x] ได้แนบลิงก์ของคลิป Youtube พร้อม Timestamp แล้ว

2022-10-01 19:01 UTC, narze requested changes
Please use https://youtu.be

2022-10-02 16:43 UTC, narze commented
waiting patiently

2022-10-02 16:48 UTC, nf0 commented
Changed krub.

2022-10-02 16:56 UTC, narze approved these changes

2022-10-02 16:56 UTC, merged