add new song
narze/torpleng pull request #81
Opened 2020-10-29 10:04 UTC by ninxxxxx

2020-10-29 11:49 UTC, narze requested changes
Please provide shortened link with exact timestamp

![image](https://user-images.githubusercontent.com/248741/97564649-74bc4e80-1a17-11eb-9b2e-a59e2f29c5fc.png)

2020-10-29 18:17 UTC, narze commented
@ninxxxxx Please fix krub

2020-10-30 01:49 UTC, ninxxxxx commented
done krub

2020-10-30 06:59 UTC, narze approved these changes
👍

2020-10-30 06:59 UTC, merged